ALTER TABLE editais
    ADD COLUMN IF NOT EXISTS modelo_formulario INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS relatorios_exigidos JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS titulo_minimo_elegibilidade VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS exige_empresa BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS porte_empresa JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS enquadramento_empresa JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS documentos_obrigatorios JSONB NOT NULL DEFAULT '[]';
