// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_tokens.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarTokenRedefinicao = `-- name: BuscarTokenRedefinicao :one
SELECT id, usuario_id, token, expirado_em, consumido_em, criado_em
FROM tokens_redefinicao
WHERE token = $1 AND consumido_em IS NULL
`

func (q *Queries) BuscarTokenRedefinicao(ctx context.Context, token string) (TokensRedefinicao, error) {
	row := q.db.QueryRow(ctx, buscarTokenRedefinicao, token)
	var i TokensRedefinicao
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Token,
		&i.ExpiradoEm,
		&i.ConsumidoEm,
		&i.CriadoEm,
	)
	return i, err
}

const consumirTokenRedefinicao = `-- name: ConsumirTokenRedefinicao :exec
UPDATE tokens_redefinicao
SET consumido_em = NOW()
WHERE token = $1
`

func (q *Queries) ConsumirTokenRedefinicao(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, consumirTokenRedefinicao, token)
	return err
}

const inserirTokenRedefinicao = `-- name: InserirTokenRedefinicao :exec
INSERT INTO tokens_redefinicao (usuario_id, token, expirado_em)
VALUES ($1, $2, $3)
`

type InserirTokenRedefinicaoParams struct {
	UsuarioID  int64
	Token      string
	ExpiradoEm pgtype.Timestamptz
}

func (q *Queries) InserirTokenRedefinicao(ctx context.Context, arg InserirTokenRedefinicaoParams) error {
	_, err := q.db.Exec(ctx, inserirTokenRedefinicao, arg.UsuarioID, arg.Token, arg.ExpiradoEm)
	return err
}
