// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_usuarios.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :exec
UPDATE usuarios
SET senha_hash = $2
WHERE id = $1
`

type AtualizarSenhaUsuarioParams struct {
	ID        int64
	SenhaHash string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.ID, arg.SenhaHash)
	return err
}

const atualizarTentativasUsuario = `-- name: AtualizarTentativasUsuario :exec
UPDATE usuarios
SET tentativas = $2, bloqueado_ate = $3
WHERE id = $1
`

type AtualizarTentativasUsuarioParams struct {
	ID           int64
	Tentativas   int32
	BloqueadoAte pgtype.Timestamptz
}

func (q *Queries) AtualizarTentativasUsuario(ctx context.Context, arg AtualizarTentativasUsuarioParams) error {
	_, err := q.db.Exec(ctx, atualizarTentativasUsuario, arg.ID, arg.Tentativas, arg.BloqueadoAte)
	return err
}

const buscarUsuarioPorCPF = `-- name: BuscarUsuarioPorCPF :one
SELECT id, nome, cpf, email, senha_hash, eh_estrangeiro, tentativas, bloqueado_ate, criado_em
FROM usuarios
WHERE cpf = $1
`

func (q *Queries) BuscarUsuarioPorCPF(ctx context.Context, cpf string) (Usuario, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorCPF, cpf)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.SenhaHash,
		&i.EhEstrangeiro,
		&i.Tentativas,
		&i.BloqueadoAte,
		&i.CriadoEm,
	)
	return i, err
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, nome, cpf, email, senha_hash, eh_estrangeiro, tentativas, bloqueado_ate, criado_em
FROM usuarios
WHERE email = $1
`

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.SenhaHash,
		&i.EhEstrangeiro,
		&i.Tentativas,
		&i.BloqueadoAte,
		&i.CriadoEm,
	)
	return i, err
}

const inserirUsuario = `-- name: InserirUsuario :one
INSERT INTO usuarios (nome, cpf, email, senha_hash, eh_estrangeiro)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, cpf, email, senha_hash, eh_estrangeiro, tentativas, bloqueado_ate, criado_em
`

type InserirUsuarioParams struct {
	Nome          string
	Cpf           string
	Email         string
	SenhaHash     string
	EhEstrangeiro bool
}

func (q *Queries) InserirUsuario(ctx context.Context, arg InserirUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, inserirUsuario,
		arg.Nome,
		arg.Cpf,
		arg.Email,
		arg.SenhaHash,
		arg.EhEstrangeiro,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.SenhaHash,
		&i.EhEstrangeiro,
		&i.Tentativas,
		&i.BloqueadoAte,
		&i.CriadoEm,
	)
	return i, err
}
