// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcpersistencia

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Editai struct {
	ID          int64
	Nome        string
	Descricao   string
	DataInicio  pgtype.Date
	DataFim     pgtype.Date
	Status      string
	TipoChamada string
	NotaDeCorte int32
	ValorGlobal int64
	CriadoEm    pgtype.Timestamptz
}

type TokensRedefinicao struct {
	ID          int64
	UsuarioID   int64
	Token       string
	ExpiradoEm  pgtype.Timestamptz
	ConsumidoEm pgtype.Timestamptz
	CriadoEm    pgtype.Timestamptz
}

type Usuario struct {
	ID            int64
	Nome          string
	Cpf           string
	Email         string
	SenhaHash     string
	EhEstrangeiro bool
	Tentativas    int32
	BloqueadoAte  pgtype.Timestamptz
	CriadoEm      pgtype.Timestamptz
}
