// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_editais.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarEdital = `-- name: AtualizarEdital :exec
UPDATE editais
SET nome = $2, descricao = $3, data_inicio = $4, data_fim = $5, status = $6, tipo_chamada = $7, nota_de_corte = $8, valor_global = $9
WHERE id = $1
`

type AtualizarEditalParams struct {
	ID          int64
	Nome        string
	Descricao   string
	DataInicio  pgtype.Date
	DataFim     pgtype.Date
	Status      string
	TipoChamada string
	NotaDeCorte int32
	ValorGlobal int64
}

func (q *Queries) AtualizarEdital(ctx context.Context, arg AtualizarEditalParams) error {
	_, err := q.db.Exec(ctx, atualizarEdital,
		arg.ID,
		arg.Nome,
		arg.Descricao,
		arg.DataInicio,
		arg.DataFim,
		arg.Status,
		arg.TipoChamada,
		arg.NotaDeCorte,
		arg.ValorGlobal,
	)
	return err
}

const buscarEditalPorID = `-- name: BuscarEditalPorID :one
SELECT id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, criado_em
FROM editais
WHERE id = $1
`

func (q *Queries) BuscarEditalPorID(ctx context.Context, id int64) (Editai, error) {
	row := q.db.QueryRow(ctx, buscarEditalPorID, id)
	var i Editai
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.TipoChamada,
		&i.NotaDeCorte,
		&i.ValorGlobal,
		&i.CriadoEm,
	)
	return i, err
}

const deletarEdital = `-- name: DeletarEdital :exec
DELETE FROM editais WHERE id = $1
`

func (q *Queries) DeletarEdital(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletarEdital, id)
	return err
}

const inserirEdital = `-- name: InserirEdital :one
INSERT INTO editais (nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, criado_em
`

type InserirEditalParams struct {
	Nome        string
	Descricao   string
	DataInicio  pgtype.Date
	DataFim     pgtype.Date
	Status      string
	TipoChamada string
	NotaDeCorte int32
	ValorGlobal int64
}

func (q *Queries) InserirEdital(ctx context.Context, arg InserirEditalParams) (Editai, error) {
	row := q.db.QueryRow(ctx, inserirEdital,
		arg.Nome,
		arg.Descricao,
		arg.DataInicio,
		arg.DataFim,
		arg.Status,
		arg.TipoChamada,
		arg.NotaDeCorte,
		arg.ValorGlobal,
	)
	var i Editai
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.TipoChamada,
		&i.NotaDeCorte,
		&i.ValorGlobal,
		&i.CriadoEm,
	)
	return i, err
}

const listarEditais = `-- name: ListarEditais :many
SELECT id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, criado_em
FROM editais
WHERE ($1 = '' OR nome ILIKE '%' || $1 || '%')
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR tipo_chamada = $3)
ORDER BY criado_em DESC
`

type ListarEditaisParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) ListarEditais(ctx context.Context, arg ListarEditaisParams) ([]Editai, error) {
	rows, err := q.db.Query(ctx, listarEditais, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Editai
	for rows.Next() {
		var i Editai
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.DataInicio,
			&i.DataFim,
			&i.Status,
			&i.TipoChamada,
			&i.NotaDeCorte,
			&i.ValorGlobal,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
