// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_editais.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarEdital = `-- name: AtualizarEdital :exec
UPDATE editais
SET nome = $2, descricao = $3, data_inicio = $4, data_fim = $5, status = $6, tipo_chamada = $7, nota_de_corte = $8, valor_global = $9,
    modelo_formulario = $10, relatorios_exigidos = $11, titulo_minimo_elegibilidade = $12, exige_empresa = $13, porte_empresa = $14, enquadramento_empresa = $15, documentos_obrigatorios = $16
WHERE id = $1
`

type AtualizarEditalParams struct {
	ID                        int64
	Nome                      string
	Descricao                 string
	DataInicio                pgtype.Date
	DataFim                   pgtype.Date
	Status                    string
	TipoChamada               string
	NotaDeCorte               int32
	ValorGlobal               int64
	ModeloFormulario          int32
	RelatoriosExigidos        []byte
	TituloMinimoElegibilidade string
	ExigeEmpresa              bool
	PorteEmpresa              []byte
	EnquadramentoEmpresa      []byte
	DocumentosObrigatorios    []byte
}

func (q *Queries) AtualizarEdital(ctx context.Context, arg AtualizarEditalParams) error {
	_, err := q.db.Exec(ctx, atualizarEdital,
		arg.ID,
		arg.Nome,
		arg.Descricao,
		arg.DataInicio,
		arg.DataFim,
		arg.Status,
		arg.TipoChamada,
		arg.NotaDeCorte,
		arg.ValorGlobal,
		arg.ModeloFormulario,
		arg.RelatoriosExigidos,
		arg.TituloMinimoElegibilidade,
		arg.ExigeEmpresa,
		arg.PorteEmpresa,
		arg.EnquadramentoEmpresa,
		arg.DocumentosObrigatorios,
	)
	return err
}

const buscarEditalPorID = `-- name: BuscarEditalPorID :one
SELECT id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, modelo_formulario, relatorios_exigidos, titulo_minimo_elegibilidade, exige_empresa, porte_empresa, enquadramento_empresa, documentos_obrigatorios, criado_em
FROM editais
WHERE id = $1
`

type BuscarEditalPorIDRow struct {
	ID                        int64
	Nome                      string
	Descricao                 string
	DataInicio                pgtype.Date
	DataFim                   pgtype.Date
	Status                    string
	TipoChamada               string
	NotaDeCorte               int32
	ValorGlobal               int64
	ModeloFormulario          int32
	RelatoriosExigidos        []byte
	TituloMinimoElegibilidade string
	ExigeEmpresa              bool
	PorteEmpresa              []byte
	EnquadramentoEmpresa      []byte
	DocumentosObrigatorios    []byte
	CriadoEm                  pgtype.Timestamptz
}

func (q *Queries) BuscarEditalPorID(ctx context.Context, id int64) (BuscarEditalPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarEditalPorID, id)
	var i BuscarEditalPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.TipoChamada,
		&i.NotaDeCorte,
		&i.ValorGlobal,
		&i.ModeloFormulario,
		&i.RelatoriosExigidos,
		&i.TituloMinimoElegibilidade,
		&i.ExigeEmpresa,
		&i.PorteEmpresa,
		&i.EnquadramentoEmpresa,
		&i.DocumentosObrigatorios,
		&i.CriadoEm,
	)
	return i, err
}

const deletarEdital = `-- name: DeletarEdital :exec
DELETE FROM editais WHERE id = $1
`

func (q *Queries) DeletarEdital(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletarEdital, id)
	return err
}

const inserirEdital = `-- name: InserirEdital :one
INSERT INTO editais (nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, modelo_formulario, relatorios_exigidos, titulo_minimo_elegibilidade, exige_empresa, porte_empresa, enquadramento_empresa, documentos_obrigatorios)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, modelo_formulario, relatorios_exigidos, titulo_minimo_elegibilidade, exige_empresa, porte_empresa, enquadramento_empresa, documentos_obrigatorios, criado_em
`

type InserirEditalParams struct {
	Nome                      string
	Descricao                 string
	DataInicio                pgtype.Date
	DataFim                   pgtype.Date
	Status                    string
	TipoChamada               string
	NotaDeCorte               int32
	ValorGlobal               int64
	ModeloFormulario          int32
	RelatoriosExigidos        []byte
	TituloMinimoElegibilidade string
	ExigeEmpresa              bool
	PorteEmpresa              []byte
	EnquadramentoEmpresa      []byte
	DocumentosObrigatorios    []byte
}

type InserirEditalRow struct {
	ID                        int64
	Nome                      string
	Descricao                 string
	DataInicio                pgtype.Date
	DataFim                   pgtype.Date
	Status                    string
	TipoChamada               string
	NotaDeCorte               int32
	ValorGlobal               int64
	ModeloFormulario          int32
	RelatoriosExigidos        []byte
	TituloMinimoElegibilidade string
	ExigeEmpresa              bool
	PorteEmpresa              []byte
	EnquadramentoEmpresa      []byte
	DocumentosObrigatorios    []byte
	CriadoEm                  pgtype.Timestamptz
}

func (q *Queries) InserirEdital(ctx context.Context, arg InserirEditalParams) (InserirEditalRow, error) {
	row := q.db.QueryRow(ctx, inserirEdital,
		arg.Nome,
		arg.Descricao,
		arg.DataInicio,
		arg.DataFim,
		arg.Status,
		arg.TipoChamada,
		arg.NotaDeCorte,
		arg.ValorGlobal,
		arg.ModeloFormulario,
		arg.RelatoriosExigidos,
		arg.TituloMinimoElegibilidade,
		arg.ExigeEmpresa,
		arg.PorteEmpresa,
		arg.EnquadramentoEmpresa,
		arg.DocumentosObrigatorios,
	)
	var i InserirEditalRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.TipoChamada,
		&i.NotaDeCorte,
		&i.ValorGlobal,
		&i.ModeloFormulario,
		&i.RelatoriosExigidos,
		&i.TituloMinimoElegibilidade,
		&i.ExigeEmpresa,
		&i.PorteEmpresa,
		&i.EnquadramentoEmpresa,
		&i.DocumentosObrigatorios,
		&i.CriadoEm,
	)
	return i, err
}

const listarEditais = `-- name: ListarEditais :many
SELECT id, nome, descricao, data_inicio, data_fim, status, tipo_chamada, nota_de_corte, valor_global, modelo_formulario, relatorios_exigidos, titulo_minimo_elegibilidade, exige_empresa, porte_empresa, enquadramento_empresa, documentos_obrigatorios, criado_em
FROM editais
WHERE ($1 = '' OR nome ILIKE '%' || $1 || '%')
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR tipo_chamada = $3)
ORDER BY criado_em DESC
`

type ListarEditaisParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

type ListarEditaisRow struct {
	ID                        int64
	Nome                      string
	Descricao                 string
	DataInicio                pgtype.Date
	DataFim                   pgtype.Date
	Status                    string
	TipoChamada               string
	NotaDeCorte               int32
	ValorGlobal               int64
	ModeloFormulario          int32
	RelatoriosExigidos        []byte
	TituloMinimoElegibilidade string
	ExigeEmpresa              bool
	PorteEmpresa              []byte
	EnquadramentoEmpresa      []byte
	DocumentosObrigatorios    []byte
	CriadoEm                  pgtype.Timestamptz
}

func (q *Queries) ListarEditais(ctx context.Context, arg ListarEditaisParams) ([]ListarEditaisRow, error) {
	rows, err := q.db.Query(ctx, listarEditais, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEditaisRow
	for rows.Next() {
		var i ListarEditaisRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.DataInicio,
			&i.DataFim,
			&i.Status,
			&i.TipoChamada,
			&i.NotaDeCorte,
			&i.ValorGlobal,
			&i.ModeloFormulario,
			&i.RelatoriosExigidos,
			&i.TituloMinimoElegibilidade,
			&i.ExigeEmpresa,
			&i.PorteEmpresa,
			&i.EnquadramentoEmpresa,
			&i.DocumentosObrigatorios,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
