// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_avaliadores.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarAvaliador = `-- name: AtualizarAvaliador :exec
UPDATE avaliadores SET
    nome = $2,
    cpf = $3,
    email = $4,
    titulacao_maxima = $5,
    area_conhecimento = $6,
    instituicao = $7,
    curriculo_resumido = $8,
    estado = $9,
    data_atualizacao = NOW()
WHERE id = $1
`

type AtualizarAvaliadorParams struct {
	ID                int64
	Nome              string
	Cpf               string
	Email             string
	TitulacaoMaxima   string
	AreaConhecimento  string
	Instituicao       string
	CurriculoResumido string
	Estado            string
}

func (q *Queries) AtualizarAvaliador(ctx context.Context, arg AtualizarAvaliadorParams) error {
	_, err := q.db.Exec(ctx, atualizarAvaliador,
		arg.ID,
		arg.Nome,
		arg.Cpf,
		arg.Email,
		arg.TitulacaoMaxima,
		arg.AreaConhecimento,
		arg.Instituicao,
		arg.CurriculoResumido,
		arg.Estado,
	)
	return err
}

const buscarAvaliadorPorCPF = `-- name: BuscarAvaliadorPorCPF :one
SELECT id, usuario_id, nome, cpf, email, titulacao_maxima, area_conhecimento, instituicao, curriculo_resumido, estado, data_cadastro, data_atualizacao FROM avaliadores WHERE cpf = $1
`

func (q *Queries) BuscarAvaliadorPorCPF(ctx context.Context, cpf string) (Avaliadore, error) {
	row := q.db.QueryRow(ctx, buscarAvaliadorPorCPF, cpf)
	var i Avaliadore
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.TitulacaoMaxima,
		&i.AreaConhecimento,
		&i.Instituicao,
		&i.CurriculoResumido,
		&i.Estado,
		&i.DataCadastro,
		&i.DataAtualizacao,
	)
	return i, err
}

const buscarAvaliadorPorID = `-- name: BuscarAvaliadorPorID :one
SELECT id, usuario_id, nome, cpf, email, titulacao_maxima, area_conhecimento, instituicao, curriculo_resumido, estado, data_cadastro, data_atualizacao FROM avaliadores WHERE id = $1
`

func (q *Queries) BuscarAvaliadorPorID(ctx context.Context, id int64) (Avaliadore, error) {
	row := q.db.QueryRow(ctx, buscarAvaliadorPorID, id)
	var i Avaliadore
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.TitulacaoMaxima,
		&i.AreaConhecimento,
		&i.Instituicao,
		&i.CurriculoResumido,
		&i.Estado,
		&i.DataCadastro,
		&i.DataAtualizacao,
	)
	return i, err
}

const buscarAvaliadorPorUsuarioID = `-- name: BuscarAvaliadorPorUsuarioID :one
SELECT id, usuario_id, nome, cpf, email, titulacao_maxima, area_conhecimento, instituicao, curriculo_resumido, estado, data_cadastro, data_atualizacao FROM avaliadores WHERE usuario_id = $1
`

func (q *Queries) BuscarAvaliadorPorUsuarioID(ctx context.Context, usuarioID int64) (Avaliadore, error) {
	row := q.db.QueryRow(ctx, buscarAvaliadorPorUsuarioID, usuarioID)
	var i Avaliadore
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.TitulacaoMaxima,
		&i.AreaConhecimento,
		&i.Instituicao,
		&i.CurriculoResumido,
		&i.Estado,
		&i.DataCadastro,
		&i.DataAtualizacao,
	)
	return i, err
}

const contarPropostasPorAvaliador = `-- name: ContarPropostasPorAvaliador :one
SELECT COUNT(*) FROM pareceres WHERE avaliador_id = $1
`

func (q *Queries) ContarPropostasPorAvaliador(ctx context.Context, avaliadorID int64) (int64, error) {
	row := q.db.QueryRow(ctx, contarPropostasPorAvaliador, avaliadorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const inserirAvaliador = `-- name: InserirAvaliador :one
INSERT INTO avaliadores (usuario_id, nome, cpf, email, titulacao_maxima, area_conhecimento, instituicao, curriculo_resumido, estado, data_cadastro, data_atualizacao)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InserirAvaliadorParams struct {
	UsuarioID         int64
	Nome              string
	Cpf               string
	Email             string
	TitulacaoMaxima   string
	AreaConhecimento  string
	Instituicao       string
	CurriculoResumido string
	Estado            string
	DataCadastro      pgtype.Timestamptz
	DataAtualizacao   pgtype.Timestamptz
}

func (q *Queries) InserirAvaliador(ctx context.Context, arg InserirAvaliadorParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirAvaliador,
		arg.UsuarioID,
		arg.Nome,
		arg.Cpf,
		arg.Email,
		arg.TitulacaoMaxima,
		arg.AreaConhecimento,
		arg.Instituicao,
		arg.CurriculoResumido,
		arg.Estado,
		arg.DataCadastro,
		arg.DataAtualizacao,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarAvaliadores = `-- name: ListarAvaliadores :many
SELECT id, usuario_id, nome, cpf, email, titulacao_maxima, area_conhecimento, instituicao, curriculo_resumido, estado, data_cadastro, data_atualizacao FROM avaliadores
WHERE ($1 = '' OR nome ILIKE '%' || $1 || '%')
  AND ($2 = '' OR cpf ILIKE '%' || $2 || '%')
  AND ($3 = '' OR area_conhecimento ILIKE '%' || $3 || '%')
  AND ($4 = '' OR estado = $4)
ORDER BY nome
`

type ListarAvaliadoresParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
}

func (q *Queries) ListarAvaliadores(ctx context.Context, arg ListarAvaliadoresParams) ([]Avaliadore, error) {
	rows, err := q.db.Query(ctx, listarAvaliadores,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avaliadore
	for rows.Next() {
		var i Avaliadore
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Nome,
			&i.Cpf,
			&i.Email,
			&i.TitulacaoMaxima,
			&i.AreaConhecimento,
			&i.Instituicao,
			&i.CurriculoResumido,
			&i.Estado,
			&i.DataCadastro,
			&i.DataAtualizacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
