// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_propostas.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarProposta = `-- name: AtualizarProposta :exec
UPDATE propostas SET
    versao = $2, status = $3,
    proponente_nome = $4, proponente_cpf = $5, proponente_rg = $6,
    proponente_genero = $7, proponente_etnia = $8,
    proponente_data_nascimento = $9,
    proponente_cep = $10, proponente_logradouro = $11, proponente_numero = $12,
    proponente_complemento = $13, proponente_bairro = $14,
    proponente_cidade = $15, proponente_uf = $16,
    proponente_telefone = $17, proponente_email = $18,
    academico_maior_titulacao = $19, academico_curso = $20,
    academico_instituicao = $21, academico_ano_conclusao = $22,
    academico_area_conhecimento = $23, empresa_vinculada = $24,
    valor_total_solicitado = $25, protocolo = $26,
    data_submissao = $27, data_atualizacao = NOW()
WHERE id = $1
`

type AtualizarPropostaParams struct {
	ID                        int64
	Versao                    int32
	Status                    string
	ProponenteNome            string
	ProponenteCpf             string
	ProponenteRg              string
	ProponenteGenero          string
	ProponenteEtnia           string
	ProponenteDataNascimento  string
	ProponenteCep             string
	ProponenteLogradouro      string
	ProponenteNumero          string
	ProponenteComplemento     string
	ProponenteBairro          string
	ProponenteCidade          string
	ProponenteUf              string
	ProponenteTelefone        string
	ProponenteEmail           string
	AcademicoMaiorTitulacao   string
	AcademicoCurso            string
	AcademicoInstituicao      string
	AcademicoAnoConclusao     int32
	AcademicoAreaConhecimento string
	EmpresaVinculada          string
	ValorTotalSolicitado      int64
	Protocolo                 string
	DataSubmissao             pgtype.Timestamptz
}

func (q *Queries) AtualizarProposta(ctx context.Context, arg AtualizarPropostaParams) error {
	_, err := q.db.Exec(ctx, atualizarProposta,
		arg.ID,
		arg.Versao,
		arg.Status,
		arg.ProponenteNome,
		arg.ProponenteCpf,
		arg.ProponenteRg,
		arg.ProponenteGenero,
		arg.ProponenteEtnia,
		arg.ProponenteDataNascimento,
		arg.ProponenteCep,
		arg.ProponenteLogradouro,
		arg.ProponenteNumero,
		arg.ProponenteComplemento,
		arg.ProponenteBairro,
		arg.ProponenteCidade,
		arg.ProponenteUf,
		arg.ProponenteTelefone,
		arg.ProponenteEmail,
		arg.AcademicoMaiorTitulacao,
		arg.AcademicoCurso,
		arg.AcademicoInstituicao,
		arg.AcademicoAnoConclusao,
		arg.AcademicoAreaConhecimento,
		arg.EmpresaVinculada,
		arg.ValorTotalSolicitado,
		arg.Protocolo,
		arg.DataSubmissao,
	)
	return err
}

const buscarPropostaPorID = `-- name: BuscarPropostaPorID :one
SELECT id, edital_id, proponente_id, protocolo, status, versao, proponente_nome, proponente_cpf, proponente_rg, proponente_genero, proponente_etnia, proponente_data_nascimento, proponente_telefone, proponente_email, academico_maior_titulacao, academico_curso, academico_instituicao, academico_ano_conclusao, academico_area_conhecimento, empresa_vinculada, valor_total_solicitado, data_submissao, data_atualizacao, criado_em, proponente_cep, proponente_logradouro, proponente_numero, proponente_complemento, proponente_bairro, proponente_cidade, proponente_uf FROM propostas WHERE id = $1
`

func (q *Queries) BuscarPropostaPorID(ctx context.Context, id int64) (Proposta, error) {
	row := q.db.QueryRow(ctx, buscarPropostaPorID, id)
	var i Proposta
	err := row.Scan(
		&i.ID,
		&i.EditalID,
		&i.ProponenteID,
		&i.Protocolo,
		&i.Status,
		&i.Versao,
		&i.ProponenteNome,
		&i.ProponenteCpf,
		&i.ProponenteRg,
		&i.ProponenteGenero,
		&i.ProponenteEtnia,
		&i.ProponenteDataNascimento,
		&i.ProponenteTelefone,
		&i.ProponenteEmail,
		&i.AcademicoMaiorTitulacao,
		&i.AcademicoCurso,
		&i.AcademicoInstituicao,
		&i.AcademicoAnoConclusao,
		&i.AcademicoAreaConhecimento,
		&i.EmpresaVinculada,
		&i.ValorTotalSolicitado,
		&i.DataSubmissao,
		&i.DataAtualizacao,
		&i.CriadoEm,
		&i.ProponenteCep,
		&i.ProponenteLogradouro,
		&i.ProponenteNumero,
		&i.ProponenteComplemento,
		&i.ProponenteBairro,
		&i.ProponenteCidade,
		&i.ProponenteUf,
	)
	return i, err
}

const buscarPropostaPorProtocolo = `-- name: BuscarPropostaPorProtocolo :one
SELECT id, edital_id, proponente_id, protocolo, status, versao, proponente_nome, proponente_cpf, proponente_rg, proponente_genero, proponente_etnia, proponente_data_nascimento, proponente_telefone, proponente_email, academico_maior_titulacao, academico_curso, academico_instituicao, academico_ano_conclusao, academico_area_conhecimento, empresa_vinculada, valor_total_solicitado, data_submissao, data_atualizacao, criado_em, proponente_cep, proponente_logradouro, proponente_numero, proponente_complemento, proponente_bairro, proponente_cidade, proponente_uf FROM propostas WHERE protocolo = $1
`

func (q *Queries) BuscarPropostaPorProtocolo(ctx context.Context, protocolo string) (Proposta, error) {
	row := q.db.QueryRow(ctx, buscarPropostaPorProtocolo, protocolo)
	var i Proposta
	err := row.Scan(
		&i.ID,
		&i.EditalID,
		&i.ProponenteID,
		&i.Protocolo,
		&i.Status,
		&i.Versao,
		&i.ProponenteNome,
		&i.ProponenteCpf,
		&i.ProponenteRg,
		&i.ProponenteGenero,
		&i.ProponenteEtnia,
		&i.ProponenteDataNascimento,
		&i.ProponenteTelefone,
		&i.ProponenteEmail,
		&i.AcademicoMaiorTitulacao,
		&i.AcademicoCurso,
		&i.AcademicoInstituicao,
		&i.AcademicoAnoConclusao,
		&i.AcademicoAreaConhecimento,
		&i.EmpresaVinculada,
		&i.ValorTotalSolicitado,
		&i.DataSubmissao,
		&i.DataAtualizacao,
		&i.CriadoEm,
		&i.ProponenteCep,
		&i.ProponenteLogradouro,
		&i.ProponenteNumero,
		&i.ProponenteComplemento,
		&i.ProponenteBairro,
		&i.ProponenteCidade,
		&i.ProponenteUf,
	)
	return i, err
}

const contarPropostasPorEdital = `-- name: ContarPropostasPorEdital :one
SELECT COUNT(*) FROM propostas WHERE edital_id = $1
`

func (q *Queries) ContarPropostasPorEdital(ctx context.Context, editalID int64) (int64, error) {
	row := q.db.QueryRow(ctx, contarPropostasPorEdital, editalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletarProposta = `-- name: DeletarProposta :exec
DELETE FROM propostas WHERE id = $1
`

func (q *Queries) DeletarProposta(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletarProposta, id)
	return err
}

const inserirProposta = `-- name: InserirProposta :one
INSERT INTO propostas (
    edital_id, proponente_id, protocolo, status, versao,
    proponente_nome, proponente_cpf, proponente_rg, proponente_genero, proponente_etnia,
    proponente_data_nascimento,
    proponente_cep, proponente_logradouro, proponente_numero, proponente_complemento,
    proponente_bairro, proponente_cidade, proponente_uf,
    proponente_telefone, proponente_email,
    academico_maior_titulacao, academico_curso, academico_instituicao, academico_ano_conclusao,
    academico_area_conhecimento, empresa_vinculada, valor_total_solicitado,
    data_submissao, data_atualizacao
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27,
    $28, NOW()
) RETURNING id, criado_em
`

type InserirPropostaParams struct {
	EditalID                  int64
	ProponenteID              int64
	Protocolo                 string
	Status                    string
	Versao                    int32
	ProponenteNome            string
	ProponenteCpf             string
	ProponenteRg              string
	ProponenteGenero          string
	ProponenteEtnia           string
	ProponenteDataNascimento  string
	ProponenteCep             string
	ProponenteLogradouro      string
	ProponenteNumero          string
	ProponenteComplemento     string
	ProponenteBairro          string
	ProponenteCidade          string
	ProponenteUf              string
	ProponenteTelefone        string
	ProponenteEmail           string
	AcademicoMaiorTitulacao   string
	AcademicoCurso            string
	AcademicoInstituicao      string
	AcademicoAnoConclusao     int32
	AcademicoAreaConhecimento string
	EmpresaVinculada          string
	ValorTotalSolicitado      int64
	DataSubmissao             pgtype.Timestamptz
}

type InserirPropostaRow struct {
	ID       int64
	CriadoEm pgtype.Timestamptz
}

func (q *Queries) InserirProposta(ctx context.Context, arg InserirPropostaParams) (InserirPropostaRow, error) {
	row := q.db.QueryRow(ctx, inserirProposta,
		arg.EditalID,
		arg.ProponenteID,
		arg.Protocolo,
		arg.Status,
		arg.Versao,
		arg.ProponenteNome,
		arg.ProponenteCpf,
		arg.ProponenteRg,
		arg.ProponenteGenero,
		arg.ProponenteEtnia,
		arg.ProponenteDataNascimento,
		arg.ProponenteCep,
		arg.ProponenteLogradouro,
		arg.ProponenteNumero,
		arg.ProponenteComplemento,
		arg.ProponenteBairro,
		arg.ProponenteCidade,
		arg.ProponenteUf,
		arg.ProponenteTelefone,
		arg.ProponenteEmail,
		arg.AcademicoMaiorTitulacao,
		arg.AcademicoCurso,
		arg.AcademicoInstituicao,
		arg.AcademicoAnoConclusao,
		arg.AcademicoAreaConhecimento,
		arg.EmpresaVinculada,
		arg.ValorTotalSolicitado,
		arg.DataSubmissao,
	)
	var i InserirPropostaRow
	err := row.Scan(&i.ID, &i.CriadoEm)
	return i, err
}

const inserirVersaoProposta = `-- name: InserirVersaoProposta :exec
INSERT INTO versoes_proposta (
    proposta_id, versao, status,
    proponente_nome, proponente_cpf, proponente_rg, proponente_genero, proponente_etnia,
    proponente_data_nascimento,
    proponente_cep, proponente_logradouro, proponente_numero, proponente_complemento,
    proponente_bairro, proponente_cidade, proponente_uf,
    proponente_telefone, proponente_email,
    academico_maior_titulacao, academico_curso, academico_instituicao, academico_ano_conclusao,
    academico_area_conhecimento, empresa_vinculada, valor_total_solicitado,
    protocolo, data_submissao
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27
)
`

type InserirVersaoPropostaParams struct {
	PropostaID                int64
	Versao                    int32
	Status                    string
	ProponenteNome            string
	ProponenteCpf             string
	ProponenteRg              string
	ProponenteGenero          string
	ProponenteEtnia           string
	ProponenteDataNascimento  string
	ProponenteCep             string
	ProponenteLogradouro      string
	ProponenteNumero          string
	ProponenteComplemento     string
	ProponenteBairro          string
	ProponenteCidade          string
	ProponenteUf              string
	ProponenteTelefone        string
	ProponenteEmail           string
	AcademicoMaiorTitulacao   string
	AcademicoCurso            string
	AcademicoInstituicao      string
	AcademicoAnoConclusao     int32
	AcademicoAreaConhecimento string
	EmpresaVinculada          string
	ValorTotalSolicitado      int64
	Protocolo                 string
	DataSubmissao             pgtype.Timestamptz
}

func (q *Queries) InserirVersaoProposta(ctx context.Context, arg InserirVersaoPropostaParams) error {
	_, err := q.db.Exec(ctx, inserirVersaoProposta,
		arg.PropostaID,
		arg.Versao,
		arg.Status,
		arg.ProponenteNome,
		arg.ProponenteCpf,
		arg.ProponenteRg,
		arg.ProponenteGenero,
		arg.ProponenteEtnia,
		arg.ProponenteDataNascimento,
		arg.ProponenteCep,
		arg.ProponenteLogradouro,
		arg.ProponenteNumero,
		arg.ProponenteComplemento,
		arg.ProponenteBairro,
		arg.ProponenteCidade,
		arg.ProponenteUf,
		arg.ProponenteTelefone,
		arg.ProponenteEmail,
		arg.AcademicoMaiorTitulacao,
		arg.AcademicoCurso,
		arg.AcademicoInstituicao,
		arg.AcademicoAnoConclusao,
		arg.AcademicoAreaConhecimento,
		arg.EmpresaVinculada,
		arg.ValorTotalSolicitado,
		arg.Protocolo,
		arg.DataSubmissao,
	)
	return err
}

const listarPropostas = `-- name: ListarPropostas :many
SELECT id, edital_id, proponente_id, protocolo, status, versao, proponente_nome, proponente_cpf, proponente_rg, proponente_genero, proponente_etnia, proponente_data_nascimento, proponente_telefone, proponente_email, academico_maior_titulacao, academico_curso, academico_instituicao, academico_ano_conclusao, academico_area_conhecimento, empresa_vinculada, valor_total_solicitado, data_submissao, data_atualizacao, criado_em, proponente_cep, proponente_logradouro, proponente_numero, proponente_complemento, proponente_bairro, proponente_cidade, proponente_uf FROM propostas
WHERE (edital_id = $1 OR $1 = 0)
  AND (proponente_id = $2 OR $2 = 0)
  AND (status = $3 OR $3 = '')
ORDER BY criado_em DESC
`

type ListarPropostasParams struct {
	EditalID     int64
	ProponenteID int64
	Status       string
}

func (q *Queries) ListarPropostas(ctx context.Context, arg ListarPropostasParams) ([]Proposta, error) {
	rows, err := q.db.Query(ctx, listarPropostas, arg.EditalID, arg.ProponenteID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposta
	for rows.Next() {
		var i Proposta
		if err := rows.Scan(
			&i.ID,
			&i.EditalID,
			&i.ProponenteID,
			&i.Protocolo,
			&i.Status,
			&i.Versao,
			&i.ProponenteNome,
			&i.ProponenteCpf,
			&i.ProponenteRg,
			&i.ProponenteGenero,
			&i.ProponenteEtnia,
			&i.ProponenteDataNascimento,
			&i.ProponenteTelefone,
			&i.ProponenteEmail,
			&i.AcademicoMaiorTitulacao,
			&i.AcademicoCurso,
			&i.AcademicoInstituicao,
			&i.AcademicoAnoConclusao,
			&i.AcademicoAreaConhecimento,
			&i.EmpresaVinculada,
			&i.ValorTotalSolicitado,
			&i.DataSubmissao,
			&i.DataAtualizacao,
			&i.CriadoEm,
			&i.ProponenteCep,
			&i.ProponenteLogradouro,
			&i.ProponenteNumero,
			&i.ProponenteComplemento,
			&i.ProponenteBairro,
			&i.ProponenteCidade,
			&i.ProponenteUf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
