// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_atribuicoes.sql

package sqlcpersistencia

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarAtribuicaoStatus = `-- name: AtualizarAtribuicaoStatus :exec
UPDATE atribuicoes_editais SET status_convite = $2 WHERE id = $1
`

type AtualizarAtribuicaoStatusParams struct {
	ID            int64
	StatusConvite string
}

func (q *Queries) AtualizarAtribuicaoStatus(ctx context.Context, arg AtualizarAtribuicaoStatusParams) error {
	_, err := q.db.Exec(ctx, atualizarAtribuicaoStatus, arg.ID, arg.StatusConvite)
	return err
}

const buscarAtribuicaoPorID = `-- name: BuscarAtribuicaoPorID :one
SELECT id, avaliador_id, edital_id, data_inicio, data_fim, status_convite, hash_anonimizacao, criado_em FROM atribuicoes_editais WHERE id = $1
`

func (q *Queries) BuscarAtribuicaoPorID(ctx context.Context, id int64) (AtribuicoesEditai, error) {
	row := q.db.QueryRow(ctx, buscarAtribuicaoPorID, id)
	var i AtribuicoesEditai
	err := row.Scan(
		&i.ID,
		&i.AvaliadorID,
		&i.EditalID,
		&i.DataInicio,
		&i.DataFim,
		&i.StatusConvite,
		&i.HashAnonimizacao,
		&i.CriadoEm,
	)
	return i, err
}

const contarAtribuicoesAtivasPorAvaliador = `-- name: ContarAtribuicoesAtivasPorAvaliador :one
SELECT COUNT(*) FROM atribuicoes_editais
WHERE avaliador_id = $1
  AND status_convite = 'aceito'
  AND data_inicio <= NOW()
  AND data_fim >= NOW()
`

func (q *Queries) ContarAtribuicoesAtivasPorAvaliador(ctx context.Context, avaliadorID int64) (int64, error) {
	row := q.db.QueryRow(ctx, contarAtribuicoesAtivasPorAvaliador, avaliadorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const inserirAtribuicao = `-- name: InserirAtribuicao :one
INSERT INTO atribuicoes_editais (avaliador_id, edital_id, data_inicio, data_fim, status_convite, hash_anonimizacao, criado_em)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InserirAtribuicaoParams struct {
	AvaliadorID      int64
	EditalID         int64
	DataInicio       pgtype.Timestamptz
	DataFim          pgtype.Timestamptz
	StatusConvite    string
	HashAnonimizacao string
	CriadoEm         pgtype.Timestamptz
}

func (q *Queries) InserirAtribuicao(ctx context.Context, arg InserirAtribuicaoParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirAtribuicao,
		arg.AvaliadorID,
		arg.EditalID,
		arg.DataInicio,
		arg.DataFim,
		arg.StatusConvite,
		arg.HashAnonimizacao,
		arg.CriadoEm,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarAtribuicoes = `-- name: ListarAtribuicoes :many
SELECT id, avaliador_id, edital_id, data_inicio, data_fim, status_convite, hash_anonimizacao, criado_em FROM atribuicoes_editais
WHERE ($1 = 0 OR avaliador_id = $1)
  AND ($2 = 0 OR edital_id = $2)
  AND ($3 = '' OR status_convite = $3)
ORDER BY criado_em DESC
`

type ListarAtribuicoesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) ListarAtribuicoes(ctx context.Context, arg ListarAtribuicoesParams) ([]AtribuicoesEditai, error) {
	rows, err := q.db.Query(ctx, listarAtribuicoes, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtribuicoesEditai
	for rows.Next() {
		var i AtribuicoesEditai
		if err := rows.Scan(
			&i.ID,
			&i.AvaliadorID,
			&i.EditalID,
			&i.DataInicio,
			&i.DataFim,
			&i.StatusConvite,
			&i.HashAnonimizacao,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAtribuicoesPorAvaliador = `-- name: ListarAtribuicoesPorAvaliador :many
SELECT id, avaliador_id, edital_id, data_inicio, data_fim, status_convite, hash_anonimizacao, criado_em FROM atribuicoes_editais WHERE avaliador_id = $1 ORDER BY criado_em DESC
`

func (q *Queries) ListarAtribuicoesPorAvaliador(ctx context.Context, avaliadorID int64) ([]AtribuicoesEditai, error) {
	rows, err := q.db.Query(ctx, listarAtribuicoesPorAvaliador, avaliadorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtribuicoesEditai
	for rows.Next() {
		var i AtribuicoesEditai
		if err := rows.Scan(
			&i.ID,
			&i.AvaliadorID,
			&i.EditalID,
			&i.DataInicio,
			&i.DataFim,
			&i.StatusConvite,
			&i.HashAnonimizacao,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAtribuicoesPorEdital = `-- name: ListarAtribuicoesPorEdital :many
SELECT id, avaliador_id, edital_id, data_inicio, data_fim, status_convite, hash_anonimizacao, criado_em FROM atribuicoes_editais WHERE edital_id = $1 ORDER BY criado_em DESC
`

func (q *Queries) ListarAtribuicoesPorEdital(ctx context.Context, editalID int64) ([]AtribuicoesEditai, error) {
	rows, err := q.db.Query(ctx, listarAtribuicoesPorEdital, editalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtribuicoesEditai
	for rows.Next() {
		var i AtribuicoesEditai
		if err := rows.Scan(
			&i.ID,
			&i.AvaliadorID,
			&i.EditalID,
			&i.DataInicio,
			&i.DataFim,
			&i.StatusConvite,
			&i.HashAnonimizacao,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
